name: group_chat
description: "BloC Trainee App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  chewie: ^1.9.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  file_picker: ^8.1.7
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  iconly: ^1.0.1
  image_picker: ^1.1.2
  lottie: ^2.7.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.2.0
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  injectable: ^2.5.0
  go_router: ^14.6.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
